docs/CONTRIBUTING.md
CONTRIBUTING.mdに、コミットメッセージでの絵文字の使い方を記載しました
closed #38
=> コミットメッセージでの絵文字の使い方を記載

src/app/loading.tsx, src/app/not-found.tsx
- ディレクトリ構成が決まっていなかったので作成
- 付随するファイルを作成
closed #61 
relate: #57 
- loading.tsx、not-found.tsx は内容を記載しないとエラーが出たのでドキュメントの内容をコピペしています
- プルリクエストのタイトル何にするか
- そういえば明確に決めていなかった...？
- 作業内容を簡潔に書けばいいか...
- loading.tsx、not-found.tsx についての勉強や使い方調査、必要であればきちんと実装
- とりあえず必要そうということで作ったので
=> 必要なディレクトリ・ファイルを作成する

src/Contributors.json
Contributors.jsonの作成と、ダミーデータの配置
closed #36 
イシューの指示そのままの実装ですが、確認をお願いします。
なし
なし
=> Contributors.jsonの作成

src/app/layout.tsx, src/components/footer.tsx
- フッターの実装
- フッターのコンポーネント化
なし
- イシュー立てずにプルリクしてみましたが、どうなんでしょうか❓
- プロジェクト名を変更する可能性があるのであれば、プロジェクト名も変数で管理できたら楽だなと思いました。
=> footerの実装・コンポーネント化

src/app/layout.tsx
NotoSansJPのフォント設定の修正をしました
- バリアブルフォントのため`weight` 削除
- 日本語フォントのため`subsets` 削除
- `subsets`削除に伴い設定が必要なため`preload` 追加
closed #82 
なし
[Next13新機能、@next/fontでフォント読み込みを高速化してみた -Zenn](https://zenn.dev/siino/articles/b42d658af571f0#googlefonts%E3%81%AEnext%2Ffont%E5%AF%BE%E5%BF%9C)
なし
=> NotoSansJPのフォント設定の修正

Contributors.json, README.md
Contributors.jsonと、それにまつわるREADMEの内容を更新しました！
closed #112
=> :wrench: chore: 記載するデータの内容を更新

README.md
チュートリアルのステップ数を修正しました！
#131 で話し合われた通り、８Stepに揃えています！
closed #137
=> チュートリアルのステップ数を修正

.prettierignore
- 問題: マークダウンファイルが整形されてしまう
- 対策: ignoreするために `.prettierignore` にマークダウンを追加
ご確認よろしくお願いいたします！
closed #103 
- [Ignoring Code · Prettier](https://prettier.io/docs/en/ignore.html)
=> .prettierignoreにmarkdownファイルを追加

.github/release.yml
リリースノートをカスタマイズするための、設定ファイルを作成しました。
closed #163 
一旦マージして、これを元にリリースノートを作成し、
それをみて、以下など？を確認・検討していければと思います！ (at #164 )
- styleやrefactorは必要か
- fixとbugFixの方が良いか
- コード関連と、その他でまとめた方がいいか
- 過去のPRのラベル付けが適切か
=> リリースノートのカスタマイズ設定を作成

src/app/page.tsx, src/components/hero-section-emoji-shower.tsx, tailwind.config.ts
- ヒーローセクションのSP、PCの実装をしました
- ヒーローセクションのヒーローイメージ（？）も実装しました
closed #193
- PC版でのヒーローイメージの実装について特段話をしていなかったな...と思いつつ、色々考えて虹のようにしてみました
- 絵文字はChatGPTに選んでもらった華やかな絵文字50個の中から選ばれるようにしています。
- Components追加したり、tailwind.config.tsにもいろいろ記述を追加しています
PC
SP
- Conceptセクションからの背景の絵文字アニメーションですが、画面外に絵文字が行く際、デバイスの横側を飛び出して、横幅が変わって戻る...といった現象を起こっているので、 `overflow: hidden` 的なもので飛び出さないように隠して調整する必要があると思いました。
=> ヒーローセクションの実装

Contributors.json
=> y_taをコントリビューターに追加

.vscode/extensions.json
`.vscode/settings.json` で Prettier 拡張を要求しているが、インストールする動線がない
ついでに ESLint も追加
closed #
=> 🔧 chore: VS Code でおすすめの拡張機能を表示する

.github/workflows/nextjs.yml
- ビルド、デプロイ前にコードをフォーマットするように記述を追加
- `permission` の記述箇所を変更
closed #262 
以下、ご意見いただきたいです。
フォーマットが実行された時のコミットメッセージで迷っています。
現状 「[GitHub Actions] コードをフォーマット」とコミットメッセージとして表示される予定です。
最初は絵文字の使用を検討しましたが、他とは違う、自動で行われるものなので、他と差別化したほうがよいかと思い、そのように設定しました。
- #261 
現状なし
=> コード自動フォーマットのため、GitHub Actionsの設定を追加

.github/workflows/nextjs.yml
- #263 がうまくいかず、とりあえずビルド、デプロイできる状態にしたい
- #260 の状態に戻す
- #262 
- #263 
なし
なし
なし
=> Revert "コード自動フォーマットのため、GitHub Actionsの設定を追加"

src/utils/contributors-grouping.ts
コードを読んでいるとタイポと思われる部分を発見したのでPRを出させていただきます。
=> [nits] contributors-grouping.ts:15のタイポを修正しました。

Contributors.json
エラー解消のためカンマを追加しました！
closed #276 
レビューガイドラインを作成してもらった直後にも関わらず、
,がないことに気が付かず、マージしてしまいました。。。！
なので、JSONの内容を正しく読み取れず、エラーが出ています！
メモ：
レビューの際は、よくガイドラインを読むようにする！！！
=> エラー解消のためカンマを追加

Contributors.json
=> hakuinをコントリビューターに追加

Contributors.json
=> add mreysei contributor

Contributors.json
=> feat(new contributors)

.idea/.gitignore, Contributors.json
=> contribution by aitorevi.dev

docs/README_EN.md
created create docs/README_EN.md and translated the README.md in English.
=> Translated the Readme.md in English

Contributors.json
=> sademban をコントリビューターに追加

Contributors.json
初めてのコントリビュート体験です！
フォークとかこんな感じで使うんですね！
よろしくお願いします🙇
=> shotaをコントリビューターに追加

src/utils/contributors-grouping.ts
=> デフォルトの背景色を修正

.github/workflows/test.yml, __tests__/contributors.test.ts, package-lock.json, package.json
=> JSON ファイルに対する、基本的なテスト項目の追加
